// This file was autogenerated by idk compile models.
// Please do not edit.

goog.provide( 'test.codemotion.models.Invoices' );
goog.provide( 'test.codemotion.models.InvoicesDatarow' );

goog.require( 'zz.models.Datarow' );
goog.require( 'zz.models.Dataset' );
goog.require( 'zz.models.enums.FieldType' );



/**
* @param {!zz.models.Dataset} dataset
* @param {?Array.<string>} opt_data
* @extends {zz.models.Datarow}
* @constructor
*/
test.codemotion.models.InvoicesDatarow = function( dataset, opt_data ){

    /**
     * @type {string}
     */
    this.id = undefined;

    /**
     * @type {string}
     */
    this.customerId = undefined;

    /**
     * @type {number}
     */
    this.discount = undefined;

    /**
     * @type {number}
     */
    this.total = undefined;



/**
* Call parent constructor.
*/
zz.models.Datarow.call( this, dataset, opt_data );
};

goog.inherits( test.codemotion.models.InvoicesDatarow, zz.models.Datarow );

/**
* @param {goog.event.EventTarget=} opt_parent
* @param {Array.<Array>=} opt_data
* @extends {zz.models.Dataset}
* @constructor
*/
test.codemotion.models.Invoices = function( opt_parent, opt_data ){

zz.models.Dataset.call( this, opt_parent, opt_data );
};
goog.inherits( test.codemotion.models.Invoices, zz.models.Dataset );

/**
* Current dataset row type.
* @constructor
* @overwrite
* @type {test.codemotion.models.InvoicesDatarow}
*/
test.codemotion.models.Invoices.prototype.DatarowConstructor = test.codemotion.models.InvoicesDatarow;

/**
* Return test.codemotion.models.InvoicesDatarow schema object.
* @override
* @returns {Object}
*/
test.codemotion.models.Invoices.prototype.getDatarowSchema = function( ){

return {
        id: {
                index: 0,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        customerId: {
                index: 1,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        discount: {
                index: 2,
                type: zz.models.enums.FieldType.NUMBER,
                required: false
        },
        total: {
                index: 3,
                type: zz.models.enums.FieldType.NUMBER,
                required: false
        }
};
};