// This file was autogenerated by idk compile models.
// Please do not edit.

goog.provide( 'test.codemotion.models.Menu' );
goog.provide( 'test.codemotion.models.MenuDatarow' );

goog.require( 'zz.models.Datarow' );
goog.require( 'zz.models.Dataset' );
goog.require( 'zz.models.enums.FieldType' );



/**
* @param {!zz.models.Dataset} dataset
* @param {?Array.<string>} opt_data
* @extends {zz.models.Datarow}
* @constructor
*/
test.codemotion.models.MenuDatarow = function( dataset, opt_data ){

    /**
     * @type {number}
     */
    this.index = undefined;

    /**
     * @type {string}
     */
    this.id = undefined;

    /**
     * @type {string}
     */
    this.cssClass = undefined;

    /**
     * @type {boolean}
     */
    this.active = undefined;

    /**
     * @type {string}
     */
    this.caption = undefined;



/**
* Call parent constructor.
*/
zz.models.Datarow.call( this, dataset, opt_data );
};

goog.inherits( test.codemotion.models.MenuDatarow, zz.models.Datarow );

/**
* @param {goog.event.EventTarget=} opt_parent
* @param {Array.<Array>=} opt_data
* @extends {zz.models.Dataset}
* @constructor
*/
test.codemotion.models.Menu = function( opt_parent, opt_data ){

zz.models.Dataset.call( this, opt_parent, opt_data );
};
goog.inherits( test.codemotion.models.Menu, zz.models.Dataset );

/**
* Current dataset row type.
* @constructor
* @overwrite
* @type {test.codemotion.models.MenuDatarow}
*/
test.codemotion.models.Menu.prototype.DatarowConstructor = test.codemotion.models.MenuDatarow;

/**
* Return test.codemotion.models.MenuDatarow schema object.
* @override
* @returns {Object}
*/
test.codemotion.models.Menu.prototype.getDatarowSchema = function( ){

return {
        index: {
                index: 0,
                type: zz.models.enums.FieldType.NUMBER,
                required: false
        },
        id: {
                index: 1,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        cssClass: {
                index: 2,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        active: {
                index: 3,
                type: zz.models.enums.FieldType.BOOLEAN,
                required: false
        },
        caption: {
                index: 4,
                type: zz.models.enums.FieldType.STRING,
                required: false
        }
};
};