// This file was autogenerated by idk compile models.
// Please do not edit.

goog.provide( 'test.codemotion.models.Products' );
goog.provide( 'test.codemotion.models.ProductsDatarow' );

goog.require( 'zz.models.Datarow' );
goog.require( 'zz.models.Dataset' );
goog.require( 'zz.models.enums.FieldType' );



/**
* @param {!zz.models.Dataset} dataset
* @param {?Array.<string>} opt_data
* @extends {zz.models.Datarow}
* @constructor
*/
test.codemotion.models.ProductsDatarow = function( dataset, opt_data ){

    /**
     * @type {string}
     */
    this.id = undefined;

    /**
     * @type {string}
     */
    this.name = undefined;

    /**
     * @type {number}
     */
    this.price = undefined;

    /**
     * @type {string}
     */
    this.amount = undefined;



/**
* Call parent constructor.
*/
zz.models.Datarow.call( this, dataset, opt_data );
};

goog.inherits( test.codemotion.models.ProductsDatarow, zz.models.Datarow );

/**
* @param {goog.event.EventTarget=} opt_parent
* @param {Array.<Array>=} opt_data
* @extends {zz.models.Dataset}
* @constructor
*/
test.codemotion.models.Products = function( opt_parent, opt_data ){

zz.models.Dataset.call( this, opt_parent, opt_data );
};
goog.inherits( test.codemotion.models.Products, zz.models.Dataset );

/**
* Current dataset row type.
* @constructor
* @overwrite
* @type {test.codemotion.models.ProductsDatarow}
*/
test.codemotion.models.Products.prototype.DatarowConstructor = test.codemotion.models.ProductsDatarow;

/**
* Return test.codemotion.models.ProductsDatarow schema object.
* @override
* @returns {Object}
*/
test.codemotion.models.Products.prototype.getDatarowSchema = function( ){

return {
        id: {
                index: 0,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        name: {
                index: 1,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        price: {
                index: 2,
                type: zz.models.enums.FieldType.NUMBER,
                required: false
        },
        amount: {
                index: 3,
                type: zz.models.enums.FieldType.STRING,
                required: false
        }
};
};